Algoritmo "Antecessor"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa Dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel Regis Silva
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis 
numero: real
antecessor: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um numero para verificar o antecessor dele: ")
leia(numero)

antecessor <- numero - 1

escreval("Antecessor: ", antecessor)

Fimalgoritmo