Algoritmo "Area_Do_Losango"
// Disciplina   : [Lógica de Programação VisualG]
// Professor   : Jailson Costa Dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : gabriel Regis Silva
// Data atual  : 27/03/2026
Var
// Seção de Declarações das variáveis 
diagonalMaior: real
diagonalMenor: real
resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o valor do Diagonal maior do Losango: ")
leia(diagonalMaior)
escreva("Digite o valor do Diagonal Menor do Lonsago: ")
leia(diagonalMenor)
resultado<- (diagonalMaior * diagonalMenor)/2
escreval("O resultado da area do Losango é: ",resultado)

Fimalgoritmo