Algoritmo "Area_do_triangulo"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa Dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel Regis Silva
// Data atual  : 27/03/2026
Var
// Seção de Declarações das variáveis 
base: real
altura: real
resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Escreva o valor da base do triangulo: ")
leia(base)
escreva("Escreva o valor da altura do triangulo: ")
leia(altura)
resultado<- (base * altura) /2
escreval("Este é o resultado da area do triangulo: ",resultado)

Fimalgoritmo