Algoritmo "Ex06_AreaRetangulo"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jailson Costa Da Silva
// Descrição   : Lê a area do retangulo recebem base e altura
// Autor(a)    : Gabriel Regis Silva
// Data atual  : 11/04/2026
Var
   // Seção de Declarações das variáveis
   base : real
   altura : real
   resultado : real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Base: ")
   leia(base)
   escreva("Altura: ")
   leia(altura)
   resultado <- base * altura
   escreval("Area: ", resultado)

Fimalgoritmo