Algoritmo "ExemploDesvioCondicionalSimples"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jailson Costa Da Silva
// Descrição   : exemplo de desvio condicional simples
// Autor(a)    : Gabriel Regis Silva
// Data atual  : 13/04/2026
Var
   // Seção de Declarações das variáveis
   idade: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite sua idade: ")
   leia(idade)
   se idade < 18 entao
      escreval("Não pode ir na casa noturna")
   fimse
Fimalgoritmo