Algoritmo "Exemplo_EstruturaDeDecisaoComposta"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jailson Costa Da Silva
// Descrição   : Lê um valor e informa se ele é menor que 10 ou maior que 10.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2026
Var
   // Seção de Declarações das variáveis
   numero1: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite um valor: ")
   leia(numero1)
   se numero1<10 entao
      escreval("O número digitado é menor  que 10.")
   senao
      escreval("O número é maior que 10.")
   fimse

Fimalgoritmo