Algoritmo "perimetro_do_circulo"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jailson Costa Da Silva
// Descrição   : Le o raio de um círculo e calcula o comprimento
// da circunferência.
// Autor(a)    : Gabriel Regis Silva
// Data atual  : 30/03/2026
Var
   // Seção de Declarações das variáveis
   raio: real
   resultado: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite o valor do raio: ")
   leia(raio)
   resultado<- 2 * 3.14 * raio
   escreva("O valor do comprimento da circunferência do ciruclo é: : ", resultado)

Fimalgoritmo