Algoritmo "SejaBemVindo2"
// Disciplina   : [Lógica de Programação]
// Professor   : Jaison Costa do Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel Regis Silva
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis
nome: caracter
sobrenome: caracter
resultado: caracter
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Escreva seu primeiro nome: " )
leia(nome)
escreva("Escreva seu segundo nome: " )
leia(sobrenome)
resultado<- nome + " " + sobrenome
escreval("Seja Bem-Vindo(a), ", resultado)

Fimalgoritmo