Algoritmo "SOMA"
// Disciplina  : [Lógica de Programação com VisualG]
// Professor  : Jaison Costa Dos Santos
// Descrição  : Solicita dois numeros para o usuario, soma e exibe o resultado
// Autor(a)   : Gabriel Regis Silva
// Data atual : 26/03/2026
Var
// Seção de Declarações das variáveis
numero1: inteiro
numero2: inteiro
resultado: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um numero inteiro: ")
leia(numero1)
escreva("Digite o segundo numero inteiro: ")
leia(numero2)
resultado<- numero1 + numero2
escreval("A soma dos números digitados é :",resultado)

Fimalgoritmo