Algoritmo "SUBTRAÇÃO"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa Dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel Regis Silva
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis 
numero1: inteiro
numero2: inteiro
resultado: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite um numero: ")
leia(numero1)
escreva("Digite o segundo numero: ")
leia(numero2)
resultado<- numero1 - numero2
escreval("A Subtração destes dois numeros é: ",resultado)
Fimalgoritmo